# Generated by Django 3.1.3 on 2020-12-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[(False, 'Not approve'), (True, 'In break')], default=False, verbose_name='Statue'),
        ),
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256, verbose_name='Reason')),
                ('status', models.BooleanField(choices=[(False, 'Processing'), (True, 'Approved')], null=True)),
                ('applydate', models.DateTimeField(auto_now_add=True, verbose_name='Applied Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user', verbose_name='User')),
            ],
        ),
    ]
