# Generated by Django 3.1.4 on 2021-01-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201222_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='applydate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='reason',
            field=models.CharField(max_length=256, verbose_name='请假原因'),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='status',
            field=models.BooleanField(choices=[(False, '审核中'), (True, '已批准')], null=True),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[(False, 'Not approve'), (True, 'In break')], default=False, verbose_name='Status'),
        ),
    ]
